package com.example.kosherbridge.bluetooth

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.net.Uri
import android.os.Binder
import android.os.Bundle

/**
 * Receives the privileged bridge binder from the app's own root process.
 *
 * The root process (spawned via `su -c "CLASSPATH=... app_process ..."`, uid 0)
 * delivers [HfpUserService]'s binder by calling this provider with the
 * `sendBinder` method and a `Bundle.putBinder` extra - the same handoff the
 * Shizuku server performs against ShizukuProvider, but without the Shizuku app.
 *
 * Security: only uid 0 (root) may hand over a binder, and the one-time token
 * generated by [RootBridge.start] must match, so a random process cannot
 * inject a fake bridge.
 */
class RootBridgeProvider : ContentProvider() {

  override fun onCreate(): Boolean = true

  override fun call(method: String?, arg: String?, extras: Bundle?): Bundle? {
    if (method != RootBridge.METHOD_SEND_BINDER) return null
    // Only the root process may hand the app its privileged binder.
    if (Binder.getCallingUid() != 0) return null
    val extras = extras ?: return null
    val token = extras.getString(RootBridge.EXTRA_TOKEN)
    if (token.isNullOrEmpty()) return null
    val binder = extras.getBinder(RootBridge.EXTRA_BINDER) ?: return null
    RootBridge.accept(binder, extras.getInt(RootBridge.EXTRA_PID, -1), token)
    return Bundle.EMPTY
  }

  override fun query(
    uri: Uri,
    projection: Array<out String>?,
    selection: String?,
    selectionArgs: Array<out String>?,
    sortOrder: String?,
  ): Cursor? = null

  override fun getType(uri: Uri): String? = null

  override fun insert(uri: Uri, values: ContentValues?): Uri? = null

  override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0

  override fun update(
    uri: Uri,
    values: ContentValues?,
    selection: String?,
    selectionArgs: Array<out String>?,
  ): Int = 0
}
