package com.example.kosherbridge.bluetooth

import android.content.ContentProvider
import android.content.ContentValues
import android.database.Cursor
import android.net.Uri
import android.os.Binder
import android.os.Bundle

/**
 * Receives the privileged bridge binder from a process this app spawned itself.
 *
 * That process is started either through `su` (uid 0) or through the player's
 * own ADB daemon (uid 2000, `shell`). Either way it delivers
 * [HfpUserService]'s binder by calling this provider with the `sendBinder`
 * method and a `Bundle.putBinder` extra - the same handoff the Shizuku server
 * performs against ShizukuProvider, without the Shizuku app.
 *
 * Security. Two independent gates, and both must pass:
 *
 *  - The caller must be one of the two uids this app can actually spawn a
 *    process as. Nothing else on the device is allowed to hand over a binder.
 *  - The one-time random token generated by [SpawnedBridge.start] must match a
 *    spawn that is currently in flight. The token is passed on the spawned
 *    process's own command line and is consumed on first use, so a binder that
 *    arrives without it - or with a stale one - is dropped.
 *
 * Admitting `shell` is not a weakening worth worrying about: anything running
 * as `shell` on the device already has ADB, and with ADB it could install,
 * replace or debug this app outright. The token is what actually keeps the
 * handoff honest.
 */
class SpawnedBridgeProvider : ContentProvider() {

  override fun onCreate(): Boolean = true

  override fun call(method: String, arg: String?, extras: Bundle?): Bundle? {
    if (method != SpawnedBridge.METHOD_SEND_BINDER) return null
    // Only a process this app could itself have spawned: uid 0 (su) or uid
    // 2000 (the shell identity an ADB connection runs commands as).
    if (Binder.getCallingUid() !in SpawnedBridge.SPAWNABLE_UIDS) return null
    val extras = extras ?: return null
    val token = extras.getString(SpawnedBridge.EXTRA_TOKEN)
    if (token.isNullOrEmpty()) return null
    val binder = extras.getBinder(SpawnedBridge.EXTRA_BINDER) ?: return null
    SpawnedBridge.accept(binder, extras.getInt(SpawnedBridge.EXTRA_PID, -1), token)
    return Bundle.EMPTY
  }

  override fun query(
    uri: Uri,
    projection: Array<out String>?,
    selection: String?,
    selectionArgs: Array<out String>?,
    sortOrder: String?,
  ): Cursor? = null

  override fun getType(uri: Uri): String? = null

  override fun insert(uri: Uri, values: ContentValues?): Uri? = null

  override fun delete(uri: Uri, selection: String?, selectionArgs: Array<out String>?): Int = 0

  override fun update(
    uri: Uri,
    values: ContentValues?,
    selection: String?,
    selectionArgs: Array<out String>?,
  ): Int = 0
}
